image : claudiababescu/dotnet-core-aws-build
stages:
  - build
  - deploy

build:
 stage: build
 script:
  - npm install
  - npx webpack --bail index.js dist/js/bundle.js --config webpack.config.production.js
  - grunt build
 artifacts:
    paths:
      - prod.html
      - dist
    expire_in: 1 week

deploy_dev:
 stage: deploy
 script:
  - echo $AWS_DEV_CREDENTIALS_JSON | base64 -d > aws-credentials.json
  - s3-upload aws-upload-dev.conf.js
 only:
   - develop
   - ci

deploy_prod:
 stage: deploy
 script:
   - echo $AWS_CREDENTIALS_JSON | base64 -d > aws-credentials.json
   - s3-upload
 only:
   - master
